### ISSUE TITLE
Request for Addition of Dynamic PV Provisioning in Metabase Helm Chart

### ISSUE THREAD

**Issue by ajay15283** [pmint93/helm-charts#104]
Hello, 

Metabase Helm chart doesn't support dynamic Persistent Volume (PV) provisioning using custom storage classes. This feature would greatly enhance flexibility and scalability in Kubernetes environments.

Could we please consider adding support for dynamic PV provisioning with custom storage classes to the Helm chart for Metabase? This addition would simplify storage management and improve user experience.

Thank you for considering this request.

**Comment by pmint93** [comment]
@ajay15283 Can you explain more about your use case ? what the purpose of PV in Metabase deployment ? why it's needed ?

**Comment by ajay15283** [comment]
@pmint93 , i was in a impression the helm chart will also create the underlying database but later found it wasnt the case.sorry for the confusion closing the issue
