### ISSUE TITLE
extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

### ISSUE THREAD

**Issue by luisdavim** [pmint93/helm-charts#13]
`networking.k8s.io/v1 Ingress` has been available for long enough, I think the chart should be updated to use it.

**Comment by pmint93** [comment]
@luisdavim yes, can you also include this in your PR #12 or perhaps open a new one ?

**Comment by luisdavim** [comment]
I'll open a new one since the changes on #12 are compatible with both versions.

**Comment by pmint93** [comment]
Yes, thanks

**Comment by luisdavim** [comment]
Opened #14 to address this.
