### ISSUE TITLE
Allow setting spec.strategy.type=Recreate

### ISSUE THREAD

**Issue by devurandom** [pmint93/helm-charts#28]
When using a volume backed by block storage it is not possible to use the same volume on different nodes at the same time: `Multi-Attach error for volume ... Volume is already used by pod(s) ...` (cf. e.g. https://stackoverflow.com/q/46887118)

Thus it would be nice if the Helm chart would allow me to set `spec.strategy.type=Recreate`, to prevent multiple pods from running at the same time (on different nodes): https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec

**Comment by pmint93** [comment]
Agree 👍 

FYI: There is another workaround that we could use affinity to schedule the new pod into the same node
