### ISSUE TITLE
Update to Metabase 0.44.6

### ISSUE THREAD

**Issue by zahir-koradia** [pmint93/helm-charts#43]
Would it be possible to have an update for metabase 0.44.6. It seems that Google made an unannounced deprecation that has affected "Sign in with Google" capability in metabase. Version 0.44.6 fixes this (relevant issue here: https://github.com/metabase/metabase/issues/26184). 

I'm do not have a lot of experience maintaining helm charts so I don't quite know how to contribute myself. If you'd prefer that I contribute this change, any guidance on how to go about doing this would be welcome.

**Comment by pmint93** [comment]
@zahir-koradia  I see no breaking changes from v0.44.3 to v0.44.6. So it's safe to run v0.44.6 with this chart, you can simply override the default value of `image.tag` in `values.yaml` to deploy your desired version.

Or if you want to contribute, simply bump the metabase & chart version, see similar PR #41

**Comment by zahir-koradia** [comment]
Thanks for the link the PR @pmint93. I've created a PR for this here: https://github.com/pmint93/helm-charts/pull/44
