### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ngk512** [pmint93/helm-charts#47]
Hi,

While installing pmint93/metabase it says failed to download.

![image](https://user-images.githubusercontent.com/47627540/205585435-e4ba8816-959f-45af-b751-6a469090c018.png)

How to resolve the issue?

**Comment by pmint93** [comment]
@ngk512  Which helm version you're using ? The chart host on github it self, so failed to download the chart usually meaning something wrong with your connection to github. Could you try it again ?

**Comment by ngk512** [comment]
@pmint93: Using helm version: version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

I followed below link to install:

https://github.com/pmint93/helm-charts/blob/master/charts/metabase/README.md

**Comment by pmint93** [comment]
@ngk512 I've tested helm version v3.8.2 working fine. If this issue persist, you can double check the connection to the chart link bellow

https://github.com/pmint93/helm-charts/releases/download/metabase-2.3.0/metabase-2.3.0.tgz

Or if you think this issue related to helm version, then you can go testing on difference version and raise an issue to the [helm project](https://github.com/helm/helm)
