### ISSUE TITLE
Can you add a port for Prometheus monitoring

### ISSUE THREAD

**Issue by sebglon** [pmint93/helm-charts#50]
Since Metabase 0.44, we can enable prometheus Monitoring endpoint.
But it require to expose the port

Documentation available here: https://www.metabase.com/docs/latest/installation-and-operation/observability-with-prometheus

**Comment by pmint93** [comment]
@sebglon
I'm not working with metabase for a while, so not sure when I have time to do that. Just here to maintain the chart for community.

It would be great if you or anyone who can contribute !

**Comment by sebglon** [comment]
Pull request created : https://github.com/pmint93/helm-charts/pull/51
