### ISSUE TITLE
Add (optional) OpenShift Route

### ISSUE THREAD

**Issue by eidottermihi** [pmint93/helm-charts#62]
First, thanks for providing a helm chart for Metabase!

We are currently deploying Metabase on OpenShift using OpenShift Templates and are currently considering a move to a deployment via (this) Helm chart. We are using OpenShift's `Route` (`route.openshift.io/v1`) instead of `Ingress`, therefore we would require some additional configuration options in the chart.

If you're open to such an addition, I'm more as happy to provide a pull request. Thanks!

**Comment by pmint93** [comment]
@eidottermihi That's great, please open a PR !
