### ISSUE TITLE
Helm chart doesn't allow pod securityContext

### ISSUE THREAD

**Issue by adrianbumbas** [pmint93/helm-charts#77]
By default the metabase pod runs as root in Kubernetes even though it defines the metabase user (UID 2000)

**Comment by pmint93** [comment]
@adrianbumbas Can you share the reference at which "it" defines metabase user with UID of 2000 ?

**Comment by adrianbumbas** [comment]
Run this command on the metabase pod

`/# cat /etc/passwd | grep metabase`
`metabase:x:2000:2000:Linux User,,,:/home/metabase:/bin/ash`

**Comment by pmint93** [comment]
I have no idea how UID of 2000 got there and there is no official document for running metabase as non-root user. It seem no one ever tried to do so.

If you have experiences in that, please share your suggestion.

**Comment by adrianbumbas** [comment]
There is absolutely no reason for metabase to run as root. Please specify `securityContext` at the deployment level and I will do some tests.

**Comment by pmint93** [comment]
@adrianbumbas You should fork/clone the chart, add securityContext and test on it first. When we confirm it work then I can merge your fork via a PR

**Comment by jhunterc15** [comment]
I created a PR that adds hooks so that you can specify your own security context. This should not be a breaking change and would allow users who have specific security restraints to use the chart. #89

**Comment by adrianbumbas** [comment]
Thanks for the update, I just tested successfully with the following settings:

```
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
```
      

You should add this in the default config for the Helm chart.
