### ISSUE TITLE
Metabase Requires Oracle JDBC driver

### ISSUE THREAD

**Issue by shakusbakus** [pmint93/helm-charts#79]
We are using chart version 2.7.4 and im seeing the chart installation fail when im spinning up a test cluster, the same version is in use with an in use cluster and was last deployed 90 days ago.

The module we use is the same for both and points to the same Helm chart but we see the below error when trying to connect to a Postgres DB.

 Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details
 
 Is there a workaround for this or a fix in a later version, any guidance would be appreciated.

**Comment by pmint93** [comment]
@shakusbakus Of course Oracle DB is not default packaged with metabase, and they are recommend to download it if you want to connect to Oracle DBs. This chart provide a method of using initContainer, you should take a look at this https://github.com/pmint93/helm-charts/blob/cd7cd689f0465cfc1dc0db66f67ae0564cd927b0/charts/metabase/values.yaml#L104-L117

Modify it to download OracleDB Driver as you need
