### ISSUE TITLE
feat: support `ServiceMonitor`

### ISSUE THREAD

**Issue by jjangga0214** [pmint93/helm-charts#83]
Hi!

Currently, it provides `monitoring.enabled` value.
However, [`ServiceMonitor`](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md) resource for Prometheus is not provisioned.
I think it's great option. 

How do you think?

Thank you very much for this chart.

Sincerely,

**Comment by pmint93** [comment]
@jjangga0214  Agree, but `serviceMonitor` should be configured with difference option than `monitoring.enabled` because of not everyone use prometheus operator

**Comment by jjangga0214** [comment]
@pmint93 Exactly. That's the convention as well. `monitoring.serviceMonitor.enabled` would be cool.
